"""books, authors, genres

Revision ID: 15bd5fad1ce0
Revises: 0131fa70b365
Create Date: 2025-05-28 09:16:22.324382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bd5fad1ce0'
down_revision: Union[str, None] = '0131fa70b365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
